# Generated by Django 5.1.6 on 2026-08-13 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('admin_inicial_creado', models.BooleanField(default=False, verbose_name='Administrador inicial creado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado del sistema',
                'verbose_name_plural': 'Estados del sistema',
            },
        ),
    ]
