# Generated by Django 5.1.6 on 2026-02-07 23:00

import api.odontogram.validators.validator_fdi
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAfectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Área Afectada',
                'verbose_name_plural': 'Áreas Afectadas',
                'db_table': 'odonto_area_afectada',
            },
        ),
        migrations.CreateModel(
            name='CategoriaDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('color_key', models.CharField(max_length=7)),
                ('prioridad_key', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Diagnóstico',
                'verbose_name_plural': 'Categorías de Diagnóstico',
                'db_table': 'odonto_categoria_diagnostico',
            },
        ),
        migrations.CreateModel(
            name='Diente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_fdi', models.CharField(choices=[('11', '11 - Incisivo central (SUPERIOR DERECHO)'), ('12', '12 - Incisivo lateral (SUPERIOR DERECHO)'), ('13', '13 - Canino (SUPERIOR DERECHO)'), ('14', '14 - Primer premolar (SUPERIOR DERECHO)'), ('15', '15 - Segundo premolar (SUPERIOR DERECHO)'), ('16', '16 - Primer molar (SUPERIOR DERECHO)'), ('17', '17 - Segundo molar (SUPERIOR DERECHO)'), ('18', '18 - Tercer molar (SUPERIOR DERECHO)'), ('21', '21 - Incisivo central (SUPERIOR IZQUIERDO)'), ('22', '22 - Incisivo lateral (SUPERIOR IZQUIERDO)'), ('23', '23 - Canino (SUPERIOR IZQUIERDO)'), ('24', '24 - Primer premolar (SUPERIOR IZQUIERDO)'), ('25', '25 - Segundo premolar (SUPERIOR IZQUIERDO)'), ('26', '26 - Primer molar (SUPERIOR IZQUIERDO)'), ('27', '27 - Segundo molar (SUPERIOR IZQUIERDO)'), ('28', '28 - Tercer molar (SUPERIOR IZQUIERDO)'), ('31', '31 - Incisivo central (INFERIOR IZQUIERDO)'), ('32', '32 - Incisivo lateral (INFERIOR IZQUIERDO)'), ('33', '33 - Canino (INFERIOR IZQUIERDO)'), ('34', '34 - Primer premolar (INFERIOR IZQUIERDO)'), ('35', '35 - Segundo premolar (INFERIOR IZQUIERDO)'), ('36', '36 - Primer molar (INFERIOR IZQUIERDO)'), ('37', '37 - Segundo molar (INFERIOR IZQUIERDO)'), ('38', '38 - Tercer molar (INFERIOR IZQUIERDO)'), ('41', '41 - Incisivo central (INFERIOR DERECHO)'), ('42', '42 - Incisivo lateral (INFERIOR DERECHO)'), ('43', '43 - Canino (INFERIOR DERECHO)'), ('44', '44 - Primer premolar (INFERIOR DERECHO)'), ('45', '45 - Segundo premolar (INFERIOR DERECHO)'), ('46', '46 - Primer molar (INFERIOR DERECHO)'), ('47', '47 - Segundo molar (INFERIOR DERECHO)'), ('48', '48 - Tercer molar (INFERIOR DERECHO)'), ('51', '51 - Incisivo central (SUPERIOR DERECHO)'), ('52', '52 - Incisivo lateral (SUPERIOR DERECHO)'), ('53', '53 - Canino (SUPERIOR DERECHO)'), ('54', '54 - Primer molar (SUPERIOR DERECHO)'), ('55', '55 - Segundo molar (SUPERIOR DERECHO)'), ('61', '61 - Incisivo central (SUPERIOR IZQUIERDO)'), ('62', '62 - Incisivo lateral (SUPERIOR IZQUIERDO)'), ('63', '63 - Canino (SUPERIOR IZQUIERDO)'), ('64', '64 - Primer molar (SUPERIOR IZQUIERDO)'), ('65', '65 - Segundo molar (SUPERIOR IZQUIERDO)'), ('71', '71 - Incisivo central (INFERIOR IZQUIERDO)'), ('72', '72 - Incisivo lateral (INFERIOR IZQUIERDO)'), ('73', '73 - Canino (INFERIOR IZQUIERDO)'), ('74', '74 - Primer molar (INFERIOR IZQUIERDO)'), ('75', '75 - Segundo molar (INFERIOR IZQUIERDO)'), ('81', '81 - Incisivo central (INFERIOR DERECHO)'), ('82', '82 - Incisivo lateral (INFERIOR DERECHO)'), ('83', '83 - Canino (INFERIOR DERECHO)'), ('84', '84 - Primer molar (INFERIOR DERECHO)'), ('85', '85 - Segundo molar (INFERIOR DERECHO)')], help_text='Código FDI internacional (11-48 permanentes, 51-85 temporales)', max_length=2, validators=[api.odontogram.validators.validator_fdi.validar_codigo_fdi])),
                ('nombre', models.CharField(blank=True, help_text='Nombre descriptivo (se genera automáticamente si está vacío)', max_length=100)),
                ('numero_3d', models.IntegerField(blank=True, editable=False, help_text='Número 3D del diente (1-52), auto-derivado desde FDI', null=True)),
                ('ausente', models.BooleanField(default=False, help_text='Marca si el diente está ausente/extraccionado')),
                ('razon_ausencia', models.CharField(blank=True, choices=[('caries', 'Pérdida por caries'), ('otra_causa', 'Pérdida por otra causa'), ('sin_erupcionar', 'Sin erupcionar'), ('exodoncia_planificada', 'Extracción planificada')], help_text='Motivo de ausencia si ausente=True', max_length=50)),
                ('movilidad', models.IntegerField(default=0, help_text='Grados de movilidad (0-3) - Formulario 033', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('recesion_gingival', models.IntegerField(default=0, help_text='Recesión gingival en mm (0-4) - Formulario 033', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['codigo_fdi'],
            },
        ),
        migrations.CreateModel(
            name='HistorialOdontograma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_cambio', models.CharField(choices=[('diagnostico_agregado', 'Diagnóstico Agregado'), ('diagnostico_modificado', 'Diagnóstico Modificado'), ('diagnostico_eliminado', 'Diagnóstico Eliminado'), ('diagnostico_tratado', 'Diagnóstico Marcado como Tratado'), ('diente_marcado_ausente', 'Diente Marcado como Ausente'), ('diente_restaurado', 'Diente Restaurado'), ('nota_agregada', 'Nota Agregada'), ('snapshot_completo', 'Snapshot Completo')], max_length=50)),
                ('descripcion', models.TextField(help_text='Descripción del cambio')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('datos_anteriores', models.JSONField(blank=True, default=dict, help_text='Estado anterior (para auditoría)')),
                ('datos_nuevos', models.JSONField(blank=True, default=dict, help_text='Estado nuevo (para auditoría)')),
                ('version_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ID de la versión del odontograma')),
            ],
            options={
                'verbose_name': 'Historial Odontograma',
                'verbose_name_plural': 'Historial Odontogramas',
                'db_table': 'odonto_historial_odontograma',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='IndicadoresSaludBucal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación lógica', null=True)),
                ('piezas_usadas_en_registro', models.JSONField(blank=True, default=dict, help_text="\n        Información de las piezas dentales usadas en este registro específico.\n        Estructura:\n        {\n            'denticion': 'permanente' | 'temporal',\n            'piezas_mapeo': {\n                '16': {\n                    'codigo_usado': '16',\n                    'es_alternativa': False,\n                    'codigo_original': '16',\n                    'disponible': True,\n                    'diente_id': 'uuid',\n                    'ausente': False\n                }\n            },\n            'estadisticas': {...}\n        }\n        ")),
                ('pieza_16_placa', models.IntegerField(blank=True, null=True)),
                ('pieza_16_calculo', models.IntegerField(blank=True, null=True)),
                ('pieza_11_placa', models.IntegerField(blank=True, null=True)),
                ('pieza_11_calculo', models.IntegerField(blank=True, null=True)),
                ('pieza_26_placa', models.IntegerField(blank=True, null=True)),
                ('pieza_26_calculo', models.IntegerField(blank=True, null=True)),
                ('pieza_36_placa', models.IntegerField(blank=True, null=True)),
                ('pieza_36_calculo', models.IntegerField(blank=True, null=True)),
                ('pieza_31_placa', models.IntegerField(blank=True, null=True)),
                ('pieza_31_calculo', models.IntegerField(blank=True, null=True)),
                ('pieza_46_placa', models.IntegerField(blank=True, null=True)),
                ('pieza_46_calculo', models.IntegerField(blank=True, null=True)),
                ('pieza_16_gingivitis', models.IntegerField(blank=True, help_text='Índice gingival pieza 16 (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('pieza_11_gingivitis', models.IntegerField(blank=True, help_text='Índice gingival pieza 11 (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('pieza_26_gingivitis', models.IntegerField(blank=True, help_text='Índice gingival pieza 26 (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('pieza_36_gingivitis', models.IntegerField(blank=True, help_text='Índice gingival pieza 36 (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('pieza_31_gingivitis', models.IntegerField(blank=True, help_text='Índice gingival pieza 31 (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('pieza_46_gingivitis', models.IntegerField(blank=True, help_text='Índice gingival pieza 46 (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('ohi_promedio_placa', models.FloatField(blank=True, null=True)),
                ('ohi_promedio_calculo', models.FloatField(blank=True, null=True)),
                ('gi_promedio_gingivitis', models.FloatField(blank=True, null=True)),
                ('enfermedad_periodontal', models.CharField(blank=True, choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('SEVERA', 'Severa')], max_length=10, null=True)),
                ('tipo_oclusion', models.CharField(blank=True, choices=[('ANGLE_I', 'Angle I'), ('ANGLE_II', 'Angle II'), ('ANGLE_III', 'Angle III')], max_length=10, null=True)),
                ('nivel_fluorosis', models.CharField(blank=True, choices=[('NINGUNA', 'No presenta'), ('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('SEVERA', 'Severa')], max_length=10, null=True)),
                ('informacion_calculo', models.JSONField(blank=True, default=dict, help_text='Información detallada de cálculos y piezas usadas')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True, help_text='False indica que el registro fue eliminado lógicamente')),
            ],
            options={
                'verbose_name': 'Indicador de Salud Bucal',
                'verbose_name_plural': 'Indicadores de Salud Bucal',
                'db_table': 'odonto_indicadores_salud_bucal',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='IndiceCariesSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_id', models.UUIDField(blank=True, db_index=True, help_text='ID de versión del odontograma (HistorialOdontograma.version_id)', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cpo_c', models.PositiveIntegerField(default=0, help_text='Dientes permanentes cariados')),
                ('cpo_p', models.PositiveIntegerField(default=0, help_text='Dientes permanentes perdidos por caries')),
                ('cpo_o', models.PositiveIntegerField(default=0, help_text='Dientes permanentes obturados')),
                ('cpo_total', models.PositiveIntegerField(default=0)),
                ('ceo_c', models.PositiveIntegerField(default=0, help_text='Dientes temporales cariados')),
                ('ceo_e', models.PositiveIntegerField(default=0, help_text='Dientes temporales con extracción indicada')),
                ('ceo_o', models.PositiveIntegerField(default=0, help_text='Dientes temporales obturados')),
                ('ceo_total', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Snapshot índice de caries',
                'verbose_name_plural': 'Snapshots índices de caries',
                'db_table': 'odonto_indice_caries_snapshot',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='OpcionAtributoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('prioridad', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opción de Atributo Clínico',
                'verbose_name_plural': 'Opciones de Atributos Clínicos',
                'db_table': 'odonto_opcion_atributo_clinico',
            },
        ),
        migrations.CreateModel(
            name='PlanTratamiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, default='Plan de Tratamiento', max_length=255)),
                ('notas_generales', models.TextField(blank=True)),
                ('version_odontograma', models.UUIDField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_edicion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plan de Tratamiento',
                'verbose_name_plural': 'Planes de Tratamiento',
                'db_table': 'odontogram_plan_tratamiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SesionTratamiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_sesion', models.PositiveIntegerField()),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='planificada', max_length=20)),
                ('diagnosticos_complicaciones', models.JSONField(default=list, help_text='Lista de diagnósticos del odontograma en esta sesión')),
                ('procedimientos', models.JSONField(default=list, help_text='Lista de procedimientos planificados/realizados')),
                ('prescripciones', models.JSONField(default=list, help_text='Medicamentos y prescripciones')),
                ('notas', models.TextField(blank=True)),
                ('fecha_edicion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de evaluación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del profesional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sesión de Tratamiento',
                'verbose_name_plural': 'Sesiones de Tratamiento',
                'db_table': 'odontogram_sesion_tratamiento',
                'ordering': ['plan_tratamiento', 'numero_sesion'],
            },
        ),
        migrations.CreateModel(
            name='SuperficieDental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('vestibular', 'Vestibular'), ('lingual', 'Lingual/Palatina'), ('oclusal', 'Oclusal/Incisal'), ('mesial', 'Mesial'), ('distal', 'Distal'), ('raiz_mesial', 'Raíz Mesial'), ('raiz_distal', 'Raíz Distal'), ('raiz_palatal', 'Raíz Palatina'), ('raiz_vestibular', 'Raíz Vestibular'), ('raiz_principal', 'Raíz Principal'), ('general', 'General')], max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo_fhir_superficie', models.CharField(blank=True, editable=False, help_text='Código automático FHIR de la superficie dental', max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Superficie Dental',
                'verbose_name_plural': 'Superficies Dentales',
                'db_table': 'odonto_superficie_dental',
            },
        ),
        migrations.CreateModel(
            name='TipoAtributoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Atributo Clínico',
                'verbose_name_plural': 'Tipos de Atributos Clínicos',
                'db_table': 'odonto_tipo_atributo_clinico',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('siglas', models.CharField(blank=True, max_length=10)),
                ('simbolo_color', models.CharField(max_length=50)),
                ('prioridad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo_icd10', models.CharField(blank=True, help_text='Código ICD-10 asociado', max_length=20)),
                ('codigo_cdt', models.CharField(blank=True, help_text='Código CDT asociado', max_length=20)),
                ('codigo_fhir', models.CharField(blank=True, help_text='Código SNOMED CT FHIR asociado', max_length=20)),
                ('tipo_recurso_fhir', models.CharField(choices=[('Condition', 'Condición (Diagnóstico)'), ('Procedure', 'Procedimiento (Tratamiento)'), ('Observation', 'Observación (Otro hallazgo)')], default='Condition', help_text='Clasifica el registro para su correcta serialización a FHIR (Condition, Procedure, etc.)', max_length=20)),
                ('simbolo_formulario_033', models.CharField(blank=True, choices=[('X_rojo', 'X rojo - Caries'), ('X_azul', 'X azul - Pérdida por caries'), ('_rojo', '| rojo - Caries necesaria (otra causa)'), ('U_rojo', 'Ü rojo - Sellante necesario'), ('U_azul', 'Ü azul - Sellante realizado'), ('r', 'r - Endodoncia por realizar'), ('_azul', '| azul - Endodoncia realizada'), ('o_azul', 'o azul - Obturado'), ('A', 'A - Ausente'), ('--', '¨---¨ - Prótesis fija indicada'), ('--_azul', '¨---¨ azul - Prótesis fija realizada'), ('-----', '(-----) - Prótesis removible indicada'), ('----_azul', '(-----) azul - Prótesis removible realizada'), ('ª', 'ª - Corona indicada'), ('ª_azul', 'ª azul - Corona realizada'), ('═', '═ - Prótesis total indicada'), ('═_azul', '═ azul - Prótesis total realizada')], max_length=50)),
                ('superficie_aplicables', models.JSONField(blank=True, default=list, help_text="Lista de categorías de superficie dental aplicables (ej: ['oclusal', 'vestibular'])")),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to='odontogram.categoriadiagnostico')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'db_table': 'odonto_diagnostico',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoAreaAfectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_relacionados', to='odontogram.areaafectada')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_relacionadas', to='odontogram.diagnostico')),
            ],
            options={
                'db_table': 'odonto_diagnostico_area',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoAtributoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos_aplicables', to='odontogram.diagnostico')),
            ],
            options={
                'db_table': 'odonto_diagnostico_atributo',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoDental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional o notas del odontólogo')),
                ('atributos_clinicos', models.JSONField(blank=True, default=dict, help_text="Opciones secundarias seleccionadas (ej: {material: 'resina', estado: 'buena'})")),
                ('prioridad_asignada', models.IntegerField(blank=True, help_text='Prioridad específica de este diagnóstico (si difiere del catálogo)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('movilidad', models.IntegerField(blank=True, choices=[(0, 'Sin movilidad'), (1, 'Movilidad 1'), (2, 'Movilidad 2'), (3, 'Movilidad 3'), (4, 'Movilidad 4')], help_text='Grado de movilidad dental (0-4) según Formulario 033', null=True)),
                ('recesion_gingival', models.IntegerField(blank=True, choices=[(0, 'Sin recesión'), (1, 'Recesión 1mm'), (2, 'Recesión 2mm'), (3, 'Recesión 3mm'), (4, 'Recesión >3mm')], help_text='Grado de recesión gingival según Formulario 033', null=True)),
                ('tipo_registro', models.CharField(choices=[('rojo', 'ROJO - Patología/hallazgo actual'), ('azul', 'AZUL - Tratamiento realizado previamente')], default='rojo', help_text='Define la coloración en el Formulario 033', max_length=10)),
                ('tipo_diagnostico', models.CharField(choices=[('presuntivo', 'Presuntivo'), ('definitivo', 'Definitivo')], default='presuntivo', help_text='Tipo de diagnóstico: Presuntivo o Definitivo', max_length=20)),
                ('estado_tratamiento', models.CharField(choices=[('diagnosticado', 'Diagnosticado'), ('en_tratamiento', 'En Tratamiento'), ('tratado', 'Tratado'), ('cancelado', 'Cancelado')], default='diagnosticado', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha del diagnóstico')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_tratamiento', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('diagnostico_catalogo', models.ForeignKey(help_text='Referencia al catálogo de diagnósticos', on_delete=django.db.models.deletion.PROTECT, related_name='instancias_aplicadas', to='odontogram.diagnostico')),
            ],
            options={
                'verbose_name': 'Diagnóstico Dental',
                'verbose_name_plural': 'Diagnósticos Dentales',
                'db_table': 'odonto_diagnostico_dental',
                'ordering': ['-fecha'],
            },
        ),
    ]
