# Generated by Django 5.1.6 on 2026-02-07 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0002_initial'),
        ('odontogram', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticodental',
            name='odontologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dientes', to='patients.paciente'),
        ),
        migrations.AddField(
            model_name='historialodontograma',
            name='diente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='odontogram.diente'),
        ),
        migrations.AddField(
            model_name='historialodontograma',
            name='odontologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_odontograma', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicadoressaludbucal',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicadores_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicadoressaludbucal',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicadores_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicadoressaludbucal',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicadores_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicadoressaludbucal',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_bucales', to='patients.paciente'),
        ),
        migrations.AddField(
            model_name='indicecariessnapshot',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_indices_caries', to='patients.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='plantratamiento',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantratamiento',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_editados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantratamiento',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantratamiento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_tratamiento', to='patients.paciente'),
        ),
        migrations.AddField(
            model_name='sesiontratamiento',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indices_caries_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='sesiontratamiento',
            name='cita',
            field=models.OneToOneField(blank=True, help_text='Cita de agenda asociada a esta sesión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesion_tratamiento', to='appointment.cita'),
        ),
        migrations.AddField(
            model_name='sesiontratamiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indices_caries_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='sesiontratamiento',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_editadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesiontratamiento',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_eliminadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesiontratamiento',
            name='odontologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesiontratamiento',
            name='plan_tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='odontogram.plantratamiento'),
        ),
        migrations.AddField(
            model_name='superficiedental',
            name='diente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superficies', to='odontogram.diente'),
        ),
        migrations.AddField(
            model_name='diagnosticodental',
            name='superficie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='odontogram.superficiedental'),
        ),
        migrations.AddField(
            model_name='opcionatributoclinico',
            name='tipo_atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='odontogram.tipoatributoclinico'),
        ),
        migrations.AddField(
            model_name='diagnosticoatributoclinico',
            name='tipo_atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_aplicables', to='odontogram.tipoatributoclinico'),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosticoareaafectada',
            unique_together={('diagnostico', 'area')},
        ),
        migrations.AlterUniqueTogether(
            name='diente',
            unique_together={('paciente', 'codigo_fdi')},
        ),
        migrations.AddIndex(
            model_name='historialodontograma',
            index=models.Index(fields=['version_id', '-fecha'], name='idx_version_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialodontograma',
            index=models.Index(fields=['diente', '-fecha'], name='idx_diente_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialodontograma',
            index=models.Index(fields=['odontologo', '-fecha'], name='idx_odontologo_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialodontograma',
            index=models.Index(fields=['diente'], name='idx_diente'),
        ),
        migrations.AddIndex(
            model_name='historialodontograma',
            index=models.Index(fields=['fecha'], name='idx_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialodontograma',
            index=models.Index(fields=['odontologo'], name='idx_odontologo'),
        ),
        migrations.AddIndex(
            model_name='historialodontograma',
            index=models.Index(fields=['version_id'], name='idx_version'),
        ),
        migrations.AddIndex(
            model_name='historialodontograma',
            index=models.Index(fields=['tipo_cambio', '-fecha'], name='idx_tipo_fecha'),
        ),
        migrations.AddIndex(
            model_name='indicadoressaludbucal',
            index=models.Index(fields=['paciente', '-fecha', 'activo'], name='idx_indicador_paciente'),
        ),
        migrations.AddIndex(
            model_name='indicadoressaludbucal',
            index=models.Index(fields=['activo'], name='idx_indicador_activo'),
        ),
        migrations.AddIndex(
            model_name='indicecariessnapshot',
            index=models.Index(fields=['paciente', '-fecha'], name='idx_indice_paciente_fecha'),
        ),
        migrations.AddIndex(
            model_name='indicecariessnapshot',
            index=models.Index(fields=['version_id', '-fecha'], name='idx_indice_version_fecha'),
        ),
        migrations.AddIndex(
            model_name='sesiontratamiento',
            index=models.Index(fields=['plan_tratamiento', 'numero_sesion'], name='odontogram__plan_tr_9a4cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='sesiontratamiento',
            index=models.Index(fields=['fecha_programada'], name='odontogram__fecha_p_140599_idx'),
        ),
        migrations.AddIndex(
            model_name='sesiontratamiento',
            index=models.Index(fields=['estado'], name='odontogram__estado_8bc53e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sesiontratamiento',
            unique_together={('plan_tratamiento', 'numero_sesion')},
        ),
        migrations.AlterUniqueTogether(
            name='superficiedental',
            unique_together={('diente', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='diagnosticodental',
            index=models.Index(fields=['superficie'], name='odonto_diag_superfi_3f28e2_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticodental',
            index=models.Index(fields=['estado_tratamiento'], name='odonto_diag_estado__b47547_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticodental',
            index=models.Index(fields=['fecha'], name='odonto_diag_fecha_03ac3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opcionatributoclinico',
            unique_together={('tipo_atributo', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='diagnosticoatributoclinico',
            unique_together={('diagnostico', 'tipo_atributo')},
        ),
    ]
