# Generated by Django 5.1.6 on 2025-10-27 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontogram', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dientes', to='patients.paciente'),
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
