# Generated by Django 5.1.6 on 2026-02-07 23:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHorario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('apertura', models.TimeField()),
                ('cierre', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de horario',
                'verbose_name_plural': 'Configuraciones de horarios',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificaciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recordatorio_citas_horas_antes', models.IntegerField(default=24, help_text='Horas de anticipación para recordatorios de citas', verbose_name='Recordatorio de citas (horas antes)')),
                ('enviar_email', models.BooleanField(default=True, verbose_name='Enviar notificaciones por email')),
                ('enviar_sms', models.BooleanField(default=False, verbose_name='Enviar notificaciones por SMS')),
                ('hora_envio_diaria', models.TimeField(default='09:00', help_text='Hora para enviar recordatorios programados', verbose_name='Hora de envío diario')),
                ('asunto_email_recordatorio', models.CharField(default='Recordatorio de cita - FamySALUD', max_length=200, verbose_name='Asunto del email de recordatorio')),
                ('plantilla_sms', models.CharField(default='Recordatorio: Tiene cita el {fecha} a las {hora} en FamySALUD', max_length=160, verbose_name='Plantilla de SMS')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de notificaciones',
                'verbose_name_plural': 'Configuraciones de notificaciones',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSeguridad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tiempo_inactividad_minutos', models.IntegerField(default=30, help_text='Minutos de inactividad antes de cerrar sesión automáticamente', verbose_name='Tiempo de inactividad (minutos)')),
                ('max_intentos_login', models.IntegerField(default=5, help_text='Número máximo de intentos fallidos antes de bloquear', verbose_name='Máximo intentos de login')),
                ('duracion_bloqueo_minutos', models.IntegerField(default=15, help_text='Minutos que permanece bloqueada la cuenta después de intentos fallidos', verbose_name='Duración de bloqueo (minutos)')),
                ('longitud_minima_password', models.IntegerField(default=8, verbose_name='Longitud mínima de contraseña')),
                ('requiere_mayusculas', models.BooleanField(default=True, verbose_name='Requerir mayúsculas')),
                ('requiere_numeros', models.BooleanField(default=True, verbose_name='Requerir números')),
                ('requiere_especiales', models.BooleanField(default=False, verbose_name='Requerir caracteres especiales')),
                ('historial_password_cantidad', models.IntegerField(default=3, help_text='Evita reutilizar las últimas N contraseñas', verbose_name='Cantidad de contraseñas anteriores a recordar')),
                ('dias_validez_password', models.IntegerField(default=90, help_text='Número de días antes de requerir cambio de contraseña', verbose_name='Días de validez de contraseña')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de seguridad',
                'verbose_name_plural': 'Configuraciones de seguridad',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoFrecuente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('CARIES', 'Caries'), ('ENFERMEDAD_PERIODONTAL', 'Enfermedad Periodontal'), ('ORTODONCIA', 'Ortodoncia'), ('ENDODONCIA', 'Endodoncia'), ('CIRUGIA', 'Cirugía'), ('PROTESIS', 'Prótesis'), ('PREVENTIVO', 'Preventivo'), ('OTRO', 'Otro')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diagnóstico frecuente',
                'verbose_name_plural': 'Diagnósticos frecuentes',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MedicamentoFrecuente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('principio_activo', models.CharField(blank=True, max_length=200)),
                ('presentacion', models.CharField(max_length=100)),
                ('dosis_habitual', models.CharField(max_length=100)),
                ('via_administracion', models.CharField(default='Oral', max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicamento frecuente',
                'verbose_name_plural': 'Medicamentos frecuentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ParametroGeneral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('STRING', 'Texto'), ('INTEGER', 'Número entero'), ('FLOAT', 'Número decimal'), ('BOOLEAN', 'Verdadero/Falso'), ('JSON', 'JSON')], default='STRING', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetro general',
                'verbose_name_plural': 'Parámetros generales',
                'ordering': ['categoria', 'clave'],
            },
        ),
    ]
