# Generated by Django 5.1.6 on 2026-02-07 23:00

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionhorario',
            name='actualizado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='config_horarios_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionhorario',
            name='creado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_horarios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionnotificaciones',
            name='actualizado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='notificaciones_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionseguridad',
            name='actualizado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='seguridad_actualizada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticofrecuente',
            name='creado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicamentofrecuente',
            name='creado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='configuracionhorario',
            unique_together={('dia_semana',)},
        ),
    ]
    
