# Generated by Django 5.1.6 on 2025-11-20 03:33

import django.core.validators
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula_pasaporte', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10, message='El número de teléfono debe tener al menos 10 dígitos.'), django.core.validators.RegexValidator(message='Solo números, mínimo 10 dígitos.', regex='^\\d{10,}$')])),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=100)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(10, message='El número de teléfono de emergencia debe tener al menos 10 dígitos.'), django.core.validators.RegexValidator(message='Solo números, mínimo 10 dígitos.', regex='^\\d{10,}$')])),
                ('alergias', models.TextField(blank=True)),
                ('enfermedades_sistemicas', models.TextField(blank=True)),
                ('habitos', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
