# Generated by Django 5.1.6 on 2026-02-07 23:00

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentesfamiliares',
            name='actualizado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='antecedentesfamiliares',
            name='creado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='antecedentespersonales',
            name='actualizado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='antecedentespersonales',
            name='creado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='constantesvitales',
            name='actualizado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='constantesvitales',
            name='creado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='examenescomplementarios',
            name='actualizado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='examenescomplementarios',
            name='creado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='examenestomatognatico',
            name='actualizado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='examenestomatognatico',
            name='creado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='actualizado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='creado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='examenestomatognatico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examen_estomatognatico', to='patients.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='examenescomplementarios',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_complementarios', to='patients.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='constantesvitales',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantes_vitales', to='patients.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='antecedentespersonales',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_personales', to='patients.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='antecedentesfamiliares',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_familiares', to='patients.paciente', verbose_name='Paciente'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['apellidos', 'nombres'], name='patients_pa_apellid_1d0a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['activo'], name='patients_pa_activo_9bd8e6_idx'),
        ),
        migrations.AddIndex(
            model_name='examenescomplementarios',
            index=models.Index(fields=['paciente'], name='patients_ex_pacient_b8a247_idx'),
        ),
        migrations.AddIndex(
            model_name='examenescomplementarios',
            index=models.Index(fields=['pedido_examenes'], name='patients_ex_pedido__f39171_idx'),
        ),
        migrations.AddIndex(
            model_name='examenescomplementarios',
            index=models.Index(fields=['informe_examenes'], name='patients_ex_informe_1c0228_idx'),
        ),
        migrations.AddIndex(
            model_name='constantesvitales',
            index=models.Index(fields=['paciente', '-fecha_consulta'], name='patients_co_pacient_6c6912_idx'),
        ),
        migrations.AddIndex(
            model_name='constantesvitales',
            index=models.Index(fields=['activo'], name='patients_co_activo_0b0d46_idx'),
        ),
        migrations.AddIndex(
            model_name='antecedentespersonales',
            index=models.Index(fields=['paciente'], name='patients_an_pacient_13adef_idx'),
        ),
        migrations.AddIndex(
            model_name='antecedentespersonales',
            index=models.Index(fields=['alergia_antibiotico'], name='patients_an_alergia_d5b9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='antecedentespersonales',
            index=models.Index(fields=['alergia_anestesia'], name='patients_an_alergia_a28039_idx'),
        ),
        migrations.AddIndex(
            model_name='antecedentespersonales',
            index=models.Index(fields=['diabetes'], name='patients_an_diabete_8e8d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='antecedentespersonales',
            index=models.Index(fields=['hipertension_arterial'], name='patients_an_hiperte_8aa865_idx'),
        ),
        migrations.AddIndex(
            model_name='antecedentespersonales',
            index=models.Index(fields=['vih_sida'], name='patients_an_vih_sid_87f497_idx'),
        ),
        migrations.AddIndex(
            model_name='antecedentespersonales',
            index=models.Index(fields=['tuberculosis'], name='patients_an_tubercu_10f8da_idx'),
        ),
        migrations.AddIndex(
            model_name='antecedentesfamiliares',
            index=models.Index(fields=['paciente'], name='patients_an_pacient_954a14_idx'),
        ),
    ]
