# Generated by Django 5.1.6 on 2026-01-28 04:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha de la cita')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('duracion', models.IntegerField(default=30, verbose_name='Duración (minutos)')),
                ('tipo_consulta', models.CharField(choices=[('PRIMERA_VEZ', 'Primera Vez'), ('CONTROL', 'Control'), ('URGENCIA', 'Urgencia'), ('LIMPIEZA', 'Limpieza Dental'), ('ORTODONCIA', 'Ortodoncia'), ('ENDODONCIA', 'Endodoncia'), ('CIRUGIA', 'Cirugía'), ('PROTESIS', 'Prótesis'), ('SESION', 'Sesión'), ('OTRO', 'Otro')], default='CONTROL', max_length=20, verbose_name='Tipo de consulta')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('ASISTIDA', 'Asistida'), ('NO_ASISTIDA', 'No Asistida'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada'), ('EN_ATENCION', 'En Atención')], default='PROGRAMADA', max_length=20, verbose_name='Estado')),
                ('motivo_consulta', models.TextField(blank=True, verbose_name='Motivo de consulta')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('motivo_cancelacion', models.TextField(blank=True, verbose_name='Motivo de cancelación')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de atención real')),
                ('recordatorio_enviado', models.BooleanField(default=False, verbose_name='Recordatorio enviado')),
                ('fecha_recordatorio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha recordatorio')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('REPROGRAMACION', 'Reprogramación'), ('CANCELACION', 'Cancelación'), ('CAMBIO_ESTADO', 'Cambio de estado')], max_length=50, verbose_name='Tipo de acción')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos nuevos')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del cambio')),
            ],
            options={
                'verbose_name': 'Historial de Cita',
                'verbose_name_plural': 'Historial de Citas',
                'db_table': 'historial_citas',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('duracion_cita', models.IntegerField(default=30, verbose_name='Duración de cita (minutos)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horario de Atención',
                'verbose_name_plural': 'Horarios de Atención',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RecordatorioCita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destinatario', models.CharField(choices=[('PACIENTE', 'Paciente'), ('ODONTOLOGO', 'Odontólogo'), ('AMBOS', 'Ambos')], default='PACIENTE', max_length=20)),
                ('tipo_recordatorio', models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_exitosamente', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
