# Generated by Django 5.1.6 on 2026-01-08 03:49

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_examenestomatognatico_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha de la cita')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('duracion', models.IntegerField(default=30, verbose_name='Duración (minutos)')),
                ('tipo_consulta', models.CharField(choices=[('PRIMERA_VEZ', 'Primera Vez'), ('CONTROL', 'Control'), ('URGENCIA', 'Urgencia'), ('LIMPIEZA', 'Limpieza Dental'), ('ORTODONCIA', 'Ortodoncia'), ('ENDODONCIA', 'Endodoncia'), ('CIRUGIA', 'Cirugía'), ('PROTESIS', 'Prótesis'), ('OTRO', 'Otro')], default='CONTROL', max_length=20, verbose_name='Tipo de consulta')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('ASISTIDA', 'Asistida'), ('NO_ASISTIDA', 'No Asistida'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada'), ('EN_ATENCION', 'En Atención')], default='PROGRAMADA', max_length=20, verbose_name='Estado')),
                ('motivo_consulta', models.TextField(blank=True, verbose_name='Motivo de consulta')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('motivo_cancelacion', models.TextField(blank=True, verbose_name='Motivo de cancelación')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de atención real')),
                ('recordatorio_enviado', models.BooleanField(default=False, verbose_name='Recordatorio enviado')),
                ('fecha_recordatorio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha recordatorio')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='citas_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelada por')),
                ('cita_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_reprogramadas', to='appointment.cita', verbose_name='Cita original')),
                ('creado_por', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('odontologo', models.ForeignKey(limit_choices_to={'rol': 'Odontologo'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_odontologo', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='patients.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('duracion_cita', models.IntegerField(default=30, verbose_name='Duración de cita (minutos)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='horarios_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_creados', to=settings.AUTH_USER_MODEL)),
                ('odontologo', models.ForeignKey(limit_choices_to={'rol': 'Odontologo'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atencion', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo')),
            ],
            options={
                'verbose_name': 'Horario de Atención',
                'verbose_name_plural': 'Horarios de Atención',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RecordatorioCita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_recordatorio', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('LLAMADA', 'Llamada')], default='EMAIL', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_exitosamente', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='appointment.cita')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha', 'odontologo'], name='appointment_fecha_bc4a70_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente', 'fecha'], name='appointment_pacient_0cbbff_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado', 'fecha'], name='appointment_estado_5cdb50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='horarioatencion',
            unique_together={('odontologo', 'dia_semana', 'hora_inicio')},
        ),
    ]
