# Generated by Django 5.1.6 on 2026-01-20 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('REPROGRAMACION', 'Reprogramación'), ('CANCELACION', 'Cancelación'), ('CAMBIO_ESTADO', 'Cambio de estado')], max_length=50, verbose_name='Tipo de acción')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos nuevos')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del cambio')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='appointment.cita', verbose_name='Cita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_citas_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó')),
            ],
            options={
                'verbose_name': 'Historial de Cita',
                'verbose_name_plural': 'Historial de Citas',
                'db_table': 'historial_citas',
                'ordering': ['-fecha_cambio'],
                'indexes': [models.Index(fields=['cita', '-fecha_cambio'], name='historial_c_cita_id_fbc48c_idx'), models.Index(fields=['-fecha_cambio'], name='historial_c_fecha_c_4608ea_idx')],
            },
        ),
    ]
