# Generated by Django 5.1.6 on 2026-01-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatoriocita',
            name='destinatario',
            field=models.CharField(choices=[('PACIENTE', 'Paciente'), ('ODONTOLOGO', 'Odontólogo'), ('AMBOS', 'Ambos')], default='PACIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='recordatoriocita',
            name='tipo_recordatorio',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=20),
        ),
    ]
