# Generated by Django 5.1.6 on 2026-02-07 23:00

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='actualizado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='citas_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelada por'),
        ),
        migrations.AddField(
            model_name='cita',
            name='cita_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_reprogramadas', to='appointment.cita', verbose_name='Cita original'),
        ),
        migrations.AddField(
            model_name='cita',
            name='creado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='odontologo',
            field=models.ForeignKey(limit_choices_to={'rol': 'Odontologo'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_odontologo', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='patients.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='historialcita',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='appointment.cita', verbose_name='Cita'),
        ),
        migrations.AddField(
            model_name='historialcita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_citas_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó'),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='actualizado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='horarios_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='creado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='odontologo',
            field=models.ForeignKey(limit_choices_to={'rol': 'Odontologo'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atencion', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo'),
        ),
        migrations.AddField(
            model_name='recordatoriocita',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='appointment.cita'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha', 'odontologo'], name='appointment_fecha_bc4a70_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente', 'fecha'], name='appointment_pacient_0cbbff_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado', 'fecha'], name='appointment_estado_5cdb50_idx'),
        ),
        migrations.AddIndex(
            model_name='historialcita',
            index=models.Index(fields=['cita', '-fecha_cambio'], name='historial_c_cita_id_fbc48c_idx'),
        ),
        migrations.AddIndex(
            model_name='historialcita',
            index=models.Index(fields=['-fecha_cambio'], name='historial_c_fecha_c_4608ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='horarioatencion',
            unique_together={('odontologo', 'dia_semana', 'hora_inicio')},
        ),
    ]
    
