# Generated by Django 5.1.6 on 2026-01-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_recordatoriocita_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatoriocita',
            name='tipo_recordatorio',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='WHATSAPP', max_length=20),
        ),
    ]
