# Generated by Django 5.1.6 on 2026-01-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_recordatoriocita_tipo_recordatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='tipo_consulta',
            field=models.CharField(choices=[('PRIMERA_VEZ', 'Primera Vez'), ('CONTROL', 'Control'), ('URGENCIA', 'Urgencia'), ('LIMPIEZA', 'Limpieza Dental'), ('ORTODONCIA', 'Ortodoncia'), ('ENDODONCIA', 'Endodoncia'), ('CIRUGIA', 'Cirugía'), ('PROTESIS', 'Prótesis'), ('SESION', 'Sesión'), ('OTRO', 'Otro')], default='CONTROL', max_length=20, verbose_name='Tipo de consulta'),
        ),
        migrations.AlterField(
            model_name='recordatoriocita',
            name='tipo_recordatorio',
            field=models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=20),
        ),
    ]
