# Generated by Django 5.1.6 on 2026-01-18 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('odontogram', '0001_initial'),
        ('patients', '0003_remove_anamnesisgeneral_alergias_detalle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bucket_name', models.CharField(max_length=255)),
                ('s3_key', models.CharField(help_text='Ruta completa dentro del bucket', max_length=1024)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size_bytes', models.BigIntegerField()),
                ('category', models.CharField(choices=[('XRAY', 'Radiografía (IMG/DICOM)'), ('LAB', 'Laboratorio (PDF)'), ('PHOTO', 'Fotografía Intraoral'), ('3D', 'Modelo 3D (STL/OBJ)'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos_clinicos', to='patients.paciente')),
                ('snapshot', models.ForeignKey(blank=True, help_text='Vincula el archivo al estado del odontograma en un momento exacto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_adjuntas', to='odontogram.historialodontograma')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinical_files',
                'indexes': [models.Index(fields=['paciente', 'created_at'], name='clinical_fi_pacient_288421_idx'), models.Index(fields=['snapshot'], name='clinical_fi_snapsho_c1ce06_idx')],
            },
        ),
    ]
