# Generated by Django 5.1.6 on 2026-01-28 08:00

# Generated by Django 5.1.6 on 2026-01-28 04:25


import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_version', models.UUIDField(blank=True, db_index=True, help_text='version_id del HistorialOdontograma (agrupa todos los cambios del mismo snapshot)', null=True)),
                ('bucket_name', models.CharField(max_length=255)),
                ('s3_key', models.CharField(help_text='Ruta completa dentro del bucket', max_length=1024)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size_bytes', models.BigIntegerField()),
                ('category', models.CharField(choices=[('XRAY', 'Radiografía (IMG/DICOM)'), ('LAB', 'Laboratorio (PDF)'), ('PHOTO', 'Fotografía Intraoral'), ('3D', 'Modelo 3D (STL/OBJ)'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clinical_files',
            },
        ),
    ]
