# Generated by Django 5.1.6 on 2026-01-21 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_files', '0001_initial'),
        ('patients', '0004_remove_consulta_actualizado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clinicalfile',
            name='clinical_fi_snapsho_c1ce06_idx',
        ),
        migrations.RemoveField(
            model_name='clinicalfile',
            name='snapshot',
        ),
        migrations.AddField(
            model_name='clinicalfile',
            name='snapshot_version',
            field=models.UUIDField(blank=True, db_index=True, help_text='version_id del HistorialOdontograma (agrupa todos los cambios del mismo snapshot)', null=True),
        ),
        migrations.AddIndex(
            model_name='clinicalfile',
            index=models.Index(fields=['snapshot_version'], name='clinical_fi_snapsho_95c9b8_idx'),
        ),
    ]
