# Generated by Django 5.1.6 on 2026-02-07 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_files', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalfile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clinicalfile',
            index=models.Index(fields=['paciente', 'created_at'], name='clinical_fi_pacient_288421_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalfile',
            index=models.Index(fields=['snapshot_version'], name='clinical_fi_snapsho_95c9b8_idx'),
        ),
    ]
