# Generated by Django 5.1.6 on 2026-02-07 23:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_historia_clinica_unica', models.CharField(blank=True, help_text='Generado automáticamente: HC-{año}{secuencia:05d}', max_length=50, null=True, unique=True, verbose_name='Número de Historia Clínica Única')),
                ('numero_archivo', models.CharField(blank=True, help_text='Generado automáticamente: ARCH-{paciente_id[:8]}', max_length=50, null=True, verbose_name='Número de Archivo')),
                ('numero_hoja', models.PositiveIntegerField(default=1, verbose_name='No. Hoja')),
                ('institucion_sistema', models.CharField(default='SISTEMA NACIONAL DE SALUD Temporal', max_length=100, verbose_name='Institución del Sistema')),
                ('unicodigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='UNICÓDIGO')),
                ('establecimiento_salud', models.CharField(blank=True, max_length=200, verbose_name='Establecimiento de Salud')),
                ('motivo_consulta', models.TextField(blank=True, verbose_name='Motivo de Consulta (Sección B)')),
                ('embarazada', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, null=True, verbose_name='¿Embarazada? (Sección B)')),
                ('enfermedad_actual', models.TextField(blank=True, verbose_name='Enfermedad Actual (Sección C)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=10, verbose_name='Estado del Historial')),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Atención')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del Profesional')),
                ('diagnosticos_cie_cargados', models.BooleanField(default=False, help_text='Indica si se han cargado diagnósticos CIE-10 en este historial', verbose_name='Diagnósticos CIE Cargados')),
                ('tipo_carga_diagnosticos', models.CharField(blank=True, choices=[('nuevos', 'Nuevos'), ('previos', 'Previos'), ('todos', 'Todos')], max_length=20, null=True, verbose_name='Tipo de Carga de Diagnósticos')),
                ('constantes_vitales_nuevas', models.BooleanField(default=False, verbose_name='¿Constantes vitales nuevas?')),
                ('motivo_consulta_nuevo', models.BooleanField(default=False, verbose_name='¿Motivo de consulta nuevo?')),
                ('enfermedad_actual_nueva', models.BooleanField(default=False, verbose_name='¿Enfermedad actual nueva?')),
            ],
            options={
                'verbose_name': 'Historial Clínico',
                'verbose_name_plural': 'Historiales Clínicos',
                'ordering': ['-fecha_atencion'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoCIEHistorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_cie', models.CharField(choices=[('PRE', 'Presuntivo'), ('DEF', 'Definitivo')], default='PRE', max_length=3, verbose_name='Tipo CIE')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diagnóstico CIE en Historial',
                'verbose_name_plural': 'Diagnósticos CIE en Historial',
                'db_table': 'clinical_diagnostico_cie_historial',
            },
        ),
        migrations.CreateModel(
            name='Form033Snapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('datos_form033', models.JSONField(help_text='Estructura JSON completa del odontograma (permanente y temporal)', verbose_name='Datos del Formulario 033')),
                ('fecha_captura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Captura')),
                ('total_dientes_permanentes', models.PositiveIntegerField(default=0, verbose_name='Total Dientes Permanentes con Diagnóstico')),
                ('total_dientes_temporales', models.PositiveIntegerField(default=0, verbose_name='Total Dientes Temporales con Diagnóstico')),
                ('total_caries', models.PositiveIntegerField(default=0, verbose_name='Total Caries Detectadas')),
                ('total_ausentes', models.PositiveIntegerField(default=0, verbose_name='Total Dientes Ausentes')),
                ('total_obturados', models.PositiveIntegerField(default=0, verbose_name='Total Dientes Obturados')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del Odontograma')),
            ],
            options={
                'verbose_name': 'Snapshot Formulario 033',
                'verbose_name_plural': 'Snapshots Formulario 033',
                'ordering': ['-fecha_captura'],
            },
        ),
    ]
    
