# Generated by Django 5.1.6 on 2026-02-03 06:16

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('odontogram', '__first__'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_historia_clinica_unica', models.CharField(blank=True, help_text='Generado automáticamente: HC-{año}{secuencia:05d}', max_length=50, null=True, unique=True, verbose_name='Número de Historia Clínica Única')),
                ('numero_archivo', models.CharField(blank=True, help_text='Generado automáticamente: ARCH-{paciente_id[:8]}', max_length=50, null=True, verbose_name='Número de Archivo')),
                ('numero_hoja', models.PositiveIntegerField(default=1, verbose_name='No. Hoja')),
                ('institucion_sistema', models.CharField(default='SISTEMA NACIONAL DE SALUD Temporal', max_length=100, verbose_name='Institución del Sistema')),
                ('unicodigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='UNICÓDIGO')),
                ('establecimiento_salud', models.CharField(blank=True, max_length=200, verbose_name='Establecimiento de Salud')),
                ('motivo_consulta', models.TextField(blank=True, verbose_name='Motivo de Consulta (Sección B)')),
                ('embarazada', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, null=True, verbose_name='¿Embarazada? (Sección B)')),
                ('enfermedad_actual', models.TextField(blank=True, verbose_name='Enfermedad Actual (Sección C)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=10, verbose_name='Estado del Historial')),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Atención')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del Profesional')),
                ('constantes_vitales_nuevas', models.BooleanField(default=False, verbose_name='¿Constantes vitales nuevas?')),
                ('motivo_consulta_nuevo', models.BooleanField(default=False, verbose_name='¿Motivo de consulta nuevo?')),
                ('enfermedad_actual_nueva', models.BooleanField(default=False, verbose_name='¿Enfermedad actual nueva?')),
                ('actualizado_por', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('antecedentes_familiares', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='patients.antecedentesfamiliares', verbose_name='Antecedentes Familiares (Sección E)')),
                ('antecedentes_personales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='patients.antecedentespersonales', verbose_name='Antecedentes Personales (Sección D)')),
                ('constantes_vitales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='patients.constantesvitales', verbose_name='Constantes Vitales (Sección F)')),
                ('creado_por', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('examen_estomatognatico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='patients.examenestomatognatico', verbose_name='Examen Estomatognático (Sección G)')),
                ('indicadores_salud_bucal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odontogram.indicadoressaludbucal', verbose_name='Indicadores de Salud Bucal')),
                ('indices_caries', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odontogram.indicecariessnapshot', verbose_name='Índices de Caries (CPO/ceo)')),
                ('odontologo_responsable', models.ForeignKey(limit_choices_to={'rol': 'Odontologo'}, on_delete=django.db.models.deletion.PROTECT, related_name='historiales_clinicos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo Responsable')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_clinicos', to='patients.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Historial Clínico',
                'verbose_name_plural': 'Historiales Clínicos',
                'ordering': ['-fecha_atencion'],
            },
        ),
        migrations.CreateModel(
            name='Form033Snapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('datos_form033', models.JSONField(help_text='Estructura JSON completa del odontograma (permanente y temporal)', verbose_name='Datos del Formulario 033')),
                ('fecha_captura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Captura')),
                ('total_dientes_permanentes', models.PositiveIntegerField(default=0, verbose_name='Total Dientes Permanentes con Diagnóstico')),
                ('total_dientes_temporales', models.PositiveIntegerField(default=0, verbose_name='Total Dientes Temporales con Diagnóstico')),
                ('total_caries', models.PositiveIntegerField(default=0, verbose_name='Total Caries Detectadas')),
                ('total_ausentes', models.PositiveIntegerField(default=0, verbose_name='Total Dientes Ausentes')),
                ('total_obturados', models.PositiveIntegerField(default=0, verbose_name='Total Dientes Obturados')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del Odontograma')),
                ('actualizado_por', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('capturado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form033_snapshots_capturados', to=settings.AUTH_USER_MODEL, verbose_name='Capturado por')),
                ('creado_por', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('historial_clinico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form033_snapshot', to='clinical_records.clinicalrecord', verbose_name='Historial Clínico Asociado')),
            ],
            options={
                'verbose_name': 'Snapshot Formulario 033',
                'verbose_name_plural': 'Snapshots Formulario 033',
                'ordering': ['-fecha_captura'],
            },
        ),
        migrations.AddIndex(
            model_name='clinicalrecord',
            index=models.Index(fields=['paciente', '-fecha_atencion'], name='clinical_re_pacient_b6bf64_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalrecord',
            index=models.Index(fields=['estado', 'activo'], name='clinical_re_estado_1107d5_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalrecord',
            index=models.Index(fields=['odontologo_responsable', '-fecha_atencion'], name='clinical_re_odontol_39c3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalrecord',
            index=models.Index(fields=['numero_historia_clinica_unica'], name='clinical_re_numero__705554_idx'),
        ),
        migrations.AddIndex(
            model_name='form033snapshot',
            index=models.Index(fields=['historial_clinico'], name='clinical_re_histori_71574d_idx'),
        ),
        migrations.AddIndex(
            model_name='form033snapshot',
            index=models.Index(fields=['fecha_captura'], name='clinical_re_fecha_c_3a66c9_idx'),
        ),
        migrations.AddIndex(
            model_name='form033snapshot',
            index=models.Index(fields=['capturado_por', '-fecha_captura'], name='clinical_re_captura_d32764_idx'),
        ),
    ]
