# Generated by Django 5.1.6 on 2026-01-28 07:59

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('motivo_consulta', models.TextField(blank=True, verbose_name='Motivo de Consulta (Sección B)')),
                ('embarazada', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, null=True, verbose_name='¿Embarazada? (Sección B)')),
                ('enfermedad_actual', models.TextField(blank=True, verbose_name='Enfermedad Actual (Sección C)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=10, verbose_name='Estado del Historial')),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Atención')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del Profesional')),
                ('institucion_sistema', models.CharField(default='SISTEMA NACIONAL DE SALUD', max_length=100, verbose_name='Institución del Sistema')),
                ('unicodigo', models.CharField(blank=True, max_length=50, verbose_name='UNICÓDIGO')),
                ('establecimiento_salud', models.CharField(blank=True, max_length=200, verbose_name='Establecimiento de Salud')),
                ('numero_hoja', models.PositiveIntegerField(default=1, verbose_name='Número de Hoja')),
                ('actualizado_por', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('antecedentes_familiares', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='patients.antecedentesfamiliares', verbose_name='Antecedentes Familiares (Sección E)')),
                ('antecedentes_personales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='patients.antecedentespersonales', verbose_name='Antecedentes Personales (Sección D)')),
                ('constantes_vitales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='patients.constantesvitales', verbose_name='Constantes Vitales (Sección F)')),
                ('creado_por', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('examen_estomatognatico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='patients.examenestomatognatico', verbose_name='Examen Estomatognático (Sección G)')),
                ('odontologo_responsable', models.ForeignKey(limit_choices_to={'rol': 'Odontologo'}, on_delete=django.db.models.deletion.PROTECT, related_name='historiales_clinicos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo Responsable')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_clinicos', to='patients.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Historial Clínico',
                'verbose_name_plural': 'Historiales Clínicos',
                'ordering': ['-fecha_atencion'],
                'indexes': [models.Index(fields=['paciente', '-fecha_atencion'], name='clinical_re_pacient_b6bf64_idx'), models.Index(fields=['estado', 'activo'], name='clinical_re_estado_1107d5_idx'), models.Index(fields=['odontologo_responsable', '-fecha_atencion'], name='clinical_re_odontol_39c3c9_idx')],
            },
        ),
    ]
