# Generated by Django 5.1.6 on 2026-02-07 23:00

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_records', '0001_initial'),
        ('odontogram', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='actualizado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='antecedentes_familiares',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='patients.antecedentesfamiliares', verbose_name='Antecedentes Familiares (Sección E)'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='antecedentes_personales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='patients.antecedentespersonales', verbose_name='Antecedentes Personales (Sección D)'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='constantes_vitales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='patients.constantesvitales', verbose_name='Constantes Vitales (Sección F)'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='creado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='examen_estomatognatico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='patients.examenestomatognatico', verbose_name='Examen Estomatognático (Sección G)'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='indicadores_salud_bucal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odontogram.indicadoressaludbucal', verbose_name='Indicadores de Salud Bucal'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='indices_caries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odontogram.indicecariessnapshot', verbose_name='Índices de Caries (CPO/ceo)'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='odontologo_responsable',
            field=models.ForeignKey(limit_choices_to={'rol': 'Odontologo'}, on_delete=django.db.models.deletion.PROTECT, related_name='historiales_clinicos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo Responsable'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_clinicos', to='patients.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='plan_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='odontogram.plantratamiento', verbose_name='Plan de Tratamiento'),
        ),
        migrations.AddField(
            model_name='diagnosticociehistorial',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos_cie_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='diagnosticociehistorial',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_cie_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='diagnosticociehistorial',
            name='diagnostico_dental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_historiales_clinicos', to='odontogram.diagnosticodental', verbose_name='Diagnóstico Dental'),
        ),
        migrations.AddField(
            model_name='diagnosticociehistorial',
            name='historial_clinico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_cie', to='clinical_records.clinicalrecord', verbose_name='Historial Clínico'),
        ),
        migrations.AddField(
            model_name='form033snapshot',
            name='actualizado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='form033snapshot',
            name='capturado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form033_snapshots_capturados', to=settings.AUTH_USER_MODEL, verbose_name='Capturado por'),
        ),
        migrations.AddField(
            model_name='form033snapshot',
            name='creado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='form033snapshot',
            name='historial_clinico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form033_snapshot', to='clinical_records.clinicalrecord', verbose_name='Historial Clínico Asociado'),
        ),
        migrations.AddIndex(
            model_name='clinicalrecord',
            index=models.Index(fields=['paciente', '-fecha_atencion'], name='clinical_re_pacient_b6bf64_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalrecord',
            index=models.Index(fields=['estado', 'activo'], name='clinical_re_estado_1107d5_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalrecord',
            index=models.Index(fields=['odontologo_responsable', '-fecha_atencion'], name='clinical_re_odontol_39c3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalrecord',
            index=models.Index(fields=['numero_historia_clinica_unica'], name='clinical_re_numero__705554_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticociehistorial',
            index=models.Index(fields=['historial_clinico', 'tipo_cie', 'activo'], name='clinical_di_histori_6b28aa_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticociehistorial',
            index=models.Index(fields=['fecha_creacion'], name='clinical_di_fecha_c_6e30dc_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticociehistorial',
            index=models.Index(fields=['activo'], name='clinical_di_activo_72d062_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosticociehistorial',
            unique_together={('historial_clinico', 'diagnostico_dental')},
        ),
        migrations.AddIndex(
            model_name='form033snapshot',
            index=models.Index(fields=['historial_clinico'], name='clinical_re_histori_71574d_idx'),
        ),
        migrations.AddIndex(
            model_name='form033snapshot',
            index=models.Index(fields=['fecha_captura'], name='clinical_re_fecha_c_3a66c9_idx'),
        ),
        migrations.AddIndex(
            model_name='form033snapshot',
            index=models.Index(fields=['capturado_por', '-fecha_captura'], name='clinical_re_captura_d32764_idx'),
        ),
    ]
    
