# Generated by Django 5.1.6 on 2026-01-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='enfermedad_actual_editada',
            field=models.TextField(blank=True, verbose_name='Enfermedad Actual (Editada)'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='frecuencia_respiratoria_editada',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia Respiratoria Editada (/min)'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='motivo_consulta_editado',
            field=models.TextField(blank=True, verbose_name='Motivo de Consulta (Editado)'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='presion_arterial_editada',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Presión Arterial Editada (mmHg)'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='pulso_editado',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pulso Editado (/min)'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='temperatura_editada',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura Editada (°C)'),
        ),
    ]
