# Generated by Django 5.1.6 on 2026-01-29 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0002_initial'),
        ('odontogram', '0003_indicadoressaludbucal_gi_promedio_gingivitis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='indicadores_salud_bucal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='odontogram.indicadoressaludbucal', verbose_name='Indicadores de Salud Bucal'),
        ),
    ]
