# Generated by Django 5.1.6 on 2026-02-08 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0002_initial'),
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='examenes_complementarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='patients.examenescomplementarios', verbose_name='Exámenes Complementarios (Sección L)'),
        ),
    ]
