# Generated by Django 5.1.6 on 2026-01-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0002_clinicalrecord_enfermedad_actual_editada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='enfermedad_actual_editada',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='frecuencia_respiratoria_editada',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='motivo_consulta_editado',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='presion_arterial_editada',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='pulso_editado',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='temperatura_editada',
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='constantes_vitales_nuevas',
            field=models.BooleanField(default=False, verbose_name='¿Constantes vitales nuevas?'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='enfermedad_actual_nueva',
            field=models.BooleanField(default=False, verbose_name='¿Enfermedad actual nueva?'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='motivo_consulta_nuevo',
            field=models.BooleanField(default=False, verbose_name='¿Motivo de consulta nuevo?'),
        ),
    ]
