# Generated by Django 5.1.6 on 2026-02-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0003_clinicalrecord_examenes_complementarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='form033snapshot',
            name='imagen_odontograma',
            field=models.ImageField(blank=True, help_text='Captura PNG del odontograma 2D renderizado en el frontend', null=True, upload_to='clinical_records/odontogramas/%Y/%m/', verbose_name='Imagen del Odontograma'),
        ),
    ]
