# Generated by Django 5.1.6 on 2026-01-25 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0003_remove_clinicalrecord_enfermedad_actual_editada_and_more'),
        ('patients', '0004_remove_consulta_actualizado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='numero_archivo',
            field=models.CharField(blank=True, help_text='Generado automáticamente: ARCH-{paciente_id[:8]}', max_length=50, null=True, verbose_name='Número de Archivo'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='numero_historia_clinica_unica',
            field=models.CharField(blank=True, help_text='Generado automáticamente: HC-{año}{secuencia:05d}', max_length=50, null=True, unique=True, verbose_name='Número de Historia Clínica Única'),
        ),
        migrations.AddIndex(
            model_name='clinicalrecord',
            index=models.Index(fields=['numero_historia_clinica_unica'], name='clinical_re_numero__705554_idx'),
        ),
    ]
