# Generated by Django 5.1.6 on 2026-01-30 19:53

import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0003_clinicalrecord_indicadores_salud_bucal'),
        ('odontogram', '0005_sesiontratamiento_actualizado_por_and_more'),
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='indices_caries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odontogram.indicecariessnapshot', verbose_name='Índices de Caries (CPO/ceo)'),
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='indicadores_salud_bucal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odontogram.indicadoressaludbucal', verbose_name='Indicadores de Salud Bucal'),
        ),
        migrations.CreateModel(
            name='IndicesCaries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('version_odontograma', models.UUIDField(blank=True, db_index=True, help_text='ID de versión del odontograma (HistorialOdontograma.version_id)', null=True)),
                ('fecha_evaluacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de evaluación')),
                ('cpo_c', models.PositiveIntegerField(default=0, verbose_name='Dientes permanentes cariados')),
                ('cpo_p', models.PositiveIntegerField(default=0, verbose_name='Dientes permanentes perdidos por caries')),
                ('cpo_o', models.PositiveIntegerField(default=0, verbose_name='Dientes permanentes obturados')),
                ('cpo_total', models.PositiveIntegerField(default=0, verbose_name='Índice CPO total')),
                ('ceo_c', models.PositiveIntegerField(default=0, verbose_name='Dientes temporales cariados')),
                ('ceo_e', models.PositiveIntegerField(default=0, verbose_name='Dientes temporales con extracción indicada')),
                ('ceo_o', models.PositiveIntegerField(default=0, verbose_name='Dientes temporales obturados')),
                ('ceo_total', models.PositiveIntegerField(default=0, verbose_name='Índice ceo total')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del profesional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indices_c_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices_caries', to='patients.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Índices de Caries',
                'verbose_name_plural': 'Índices de Caries',
                'ordering': ['-fecha_evaluacion'],
                'indexes': [models.Index(fields=['paciente', '-fecha_evaluacion'], name='clinical_re_pacient_e6f0a0_idx'), models.Index(fields=['activo'], name='clinical_re_activo_545e5e_idx')],
            },
        ),
    ]
