# Generated by Django 5.1.6 on 2026-02-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0004_form033snapshot_imagen_odontograma'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticociehistorial',
            name='codigo_cie_personalizado',
            field=models.CharField(blank=True, help_text='Permite al profesional adaptar el código CIE-10 (ej. K08.1). Si se deja en blanco se usa el código del catálogo.', max_length=20, null=True, verbose_name='Código CIE-10 personalizado'),
        ),
    ]
