# Generated by Django 5.1.6 on 2026-01-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0004_clinicalrecord_numero_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalrecord',
            name='numero_hoja',
            field=models.PositiveIntegerField(default=1, verbose_name='No. Hoja'),
        ),
    ]
