# Generated by Django 5.1.6 on 2026-01-31 18:02

import django.core.validators
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0004_clinicalrecord_indices_caries_and_more'),
        ('odontogram', '0006_diagnosticodental_tipo_diagnostico'),
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoCIEHistorial',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_fdi', models.CharField(max_length=2, verbose_name='Código FDI')),
                ('superficie_nombre', models.CharField(max_length=50, verbose_name='Superficie')),
                ('diagnostico_nombre', models.CharField(max_length=100, verbose_name='Diagnóstico')),
                ('diagnostico_siglas', models.CharField(max_length=10, verbose_name='Siglas')),
                ('codigo_cie10', models.CharField(max_length=20, verbose_name='Código CIE-10')),
                ('codigo_cdt', models.CharField(blank=True, max_length=20, verbose_name='Código CDT')),
                ('tipo_diagnostico', models.CharField(choices=[('presuntivo', 'Presuntivo (PRE)'), ('definitivo', 'Definitivo (DEF)')], default='presuntivo', max_length=20, verbose_name='Tipo de Diagnóstico')),
                ('prioridad_asignada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Prioridad Asignada')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción/Notas')),
                ('fecha_evaluacion', models.DateField(verbose_name='Fecha de Evaluación')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_cie_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('diagnostico_dental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones_historial', to='odontogram.diagnosticodental', verbose_name='Diagnóstico Dental Original')),
                ('historial_clinico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_cie', to='clinical_records.clinicalrecord', verbose_name='Historial Clínico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_cie_historial', to='patients.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Diagnóstico CIE Historial',
                'verbose_name_plural': 'Diagnósticos CIE Historial',
                'db_table': 'clinical_diagnostico_cie_historial',
                'ordering': ['fecha_evaluacion', 'codigo_fdi', 'superficie_nombre'],
            },
        ),
        migrations.DeleteModel(
            name='IndicesCaries',
        ),
        migrations.AddIndex(
            model_name='diagnosticociehistorial',
            index=models.Index(fields=['paciente', 'activo', '-fecha_evaluacion'], name='clinical_di_pacient_b3f86e_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticociehistorial',
            index=models.Index(fields=['historial_clinico', 'activo'], name='clinical_di_histori_1c8b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticociehistorial',
            index=models.Index(fields=['codigo_cie10'], name='clinical_di_codigo__b01be6_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticociehistorial',
            index=models.Index(fields=['tipo_diagnostico'], name='clinical_di_tipo_di_97cdfc_idx'),
        ),
    ]
