# Generated by Django 5.1.6 on 2026-01-31 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0005_diagnosticociehistorial_delete_indicescaries_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiagnosticoCIEHistorial',
        ),
    ]
