# Generated by Django 5.1.6 on 2026-01-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0005_alter_clinicalrecord_numero_hoja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalrecord',
            name='institucion_sistema',
            field=models.CharField(default='SISTEMA NACIONAL DE SALUD Temporal', max_length=100, verbose_name='Institución del Sistema'),
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='unicodigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UNICÓDIGO'),
        ),
    ]
