# Generated by Django 5.1.6 on 2026-01-27 23:14

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0006_alter_clinicalrecord_institucion_sistema_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form033Snapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('datos_form033', models.JSONField(help_text='Estructura JSON completa del odontograma (permanente y temporal)', verbose_name='Datos del Formulario 033')),
                ('fecha_captura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Captura')),
                ('total_dientes_permanentes', models.PositiveIntegerField(default=0, verbose_name='Total Dientes Permanentes con Diagnóstico')),
                ('total_dientes_temporales', models.PositiveIntegerField(default=0, verbose_name='Total Dientes Temporales con Diagnóstico')),
                ('total_caries', models.PositiveIntegerField(default=0, verbose_name='Total Caries Detectadas')),
                ('total_ausentes', models.PositiveIntegerField(default=0, verbose_name='Total Dientes Ausentes')),
                ('total_obturados', models.PositiveIntegerField(default=0, verbose_name='Total Dientes Obturados')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del Odontograma')),
                ('actualizado_por', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('capturado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form033_snapshots_capturados', to=settings.AUTH_USER_MODEL, verbose_name='Capturado por')),
                ('creado_por', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('historial_clinico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form033_snapshot', to='clinical_records.clinicalrecord', verbose_name='Historial Clínico Asociado')),
            ],
            options={
                'verbose_name': 'Snapshot Formulario 033',
                'verbose_name_plural': 'Snapshots Formulario 033',
                'ordering': ['-fecha_captura'],
                'indexes': [models.Index(fields=['historial_clinico'], name='clinical_re_histori_71574d_idx'), models.Index(fields=['fecha_captura'], name='clinical_re_fecha_c_3a66c9_idx'), models.Index(fields=['capturado_por', '-fecha_captura'], name='clinical_re_captura_d32764_idx')],
            },
        ),
    ]
