# Generated by Django 5.1.6 on 2026-01-31 21:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0006_delete_diagnosticociehistorial'),
        ('odontogram', '0006_diagnosticodental_tipo_diagnostico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='tipo_carga_diagnosticos',
            field=models.CharField(blank=True, choices=[('nuevos', 'Solo nuevos diagnósticos'), ('todos', 'Todos los diagnósticos del snapshot')], max_length=10, null=True, verbose_name='Tipo de carga de diagnósticos'),
        ),
        migrations.CreateModel(
            name='DiagnosticoCIEHistorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_cie', models.CharField(choices=[('PRE', 'Presuntivo'), ('DEF', 'Definitivo')], default='PRE', max_length=3, verbose_name='Tipo CIE')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_cie_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('diagnostico_dental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_historiales_clinicos', to='odontogram.diagnosticodental', verbose_name='Diagnóstico Dental')),
                ('historial_clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_cie', to='clinical_records.clinicalrecord', verbose_name='Historial Clínico')),
            ],
            options={
                'verbose_name': 'Diagnóstico CIE en Historial',
                'verbose_name_plural': 'Diagnósticos CIE en Historial',
                'db_table': 'clinical_diagnostico_cie_historial',
                'indexes': [models.Index(fields=['historial_clinico', 'tipo_cie'], name='clinical_di_histori_46c19b_idx'), models.Index(fields=['fecha_creacion'], name='clinical_di_fecha_c_6e30dc_idx')],
                'unique_together': {('historial_clinico', 'diagnostico_dental')},
            },
        ),
    ]
