# Generated by Django 5.1.6 on 2026-02-01 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0007_clinicalrecord_tipo_carga_diagnosticos_and_more'),
        ('odontogram', '0006_diagnosticodental_tipo_diagnostico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='diagnosticociehistorial',
            name='clinical_di_histori_46c19b_idx',
        ),
        migrations.AddField(
            model_name='diagnosticociehistorial',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='diagnosticociehistorial',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos_cie_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddIndex(
            model_name='diagnosticociehistorial',
            index=models.Index(fields=['historial_clinico', 'tipo_cie', 'activo'], name='clinical_di_histori_6b28aa_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticociehistorial',
            index=models.Index(fields=['activo'], name='clinical_di_activo_72d062_idx'),
        ),
    ]
