# Generated by Django 5.1.6 on 2026-02-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0008_remove_diagnosticociehistorial_clinical_di_histori_46c19b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='diagnosticos_cie_cargados',
            field=models.BooleanField(default=False, help_text='Indica si se han cargado diagnósticos CIE-10 en este historial', verbose_name='Diagnósticos CIE Cargados'),
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='tipo_carga_diagnosticos',
            field=models.CharField(blank=True, choices=[('nuevos', 'Nuevos'), ('previos', 'Previos'), ('todos', 'Todos')], max_length=20, null=True, verbose_name='Tipo de Carga de Diagnósticos'),
        ),
    ]
