# Generated by Django 5.1.6 on 2026-02-03 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0009_clinicalrecord_diagnosticos_cie_cargados_and_more'),
        ('odontogram', '0006_diagnosticodental_tipo_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='plan_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='odontogram.plantratamiento', verbose_name='Plan de Tratamiento'),
        ),
    ]
