# Generated by Django 5.1.6 on 2026-02-05 22:51

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0010_clinicalrecord_plan_tratamiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTratamientoSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('plan_original_id', models.UUIDField(help_text='UUID del PlanTratamiento original', verbose_name='ID del Plan Original')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Plan')),
                ('notas_generales', models.TextField(blank=True, verbose_name='Notas Generales')),
                ('sesiones', models.JSONField(default=list, help_text='Array de sesiones con sus procedimientos y prescripciones', verbose_name='Sesiones del Plan')),
                ('version_odontograma', models.UUIDField(blank=True, null=True, verbose_name='Versión del Odontograma')),
                ('fecha_creacion_plan_original', models.DateTimeField(verbose_name='Fecha Creación Plan Original')),
                ('fecha_snapshot', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Snapshot')),
                ('observaciones_snapshot', models.TextField(blank=True, help_text='Notas sobre por qué se creó este snapshot', verbose_name='Observaciones del Snapshot')),
                ('actualizado_por', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('creado_por_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_plan_creados', to=settings.AUTH_USER_MODEL, verbose_name='Snapshot Creado Por')),
                ('historial_clinico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_tratamiento_snapshot', to='clinical_records.clinicalrecord', verbose_name='Historial Clínico')),
            ],
            options={
                'verbose_name': 'Snapshot de Plan de Tratamiento',
                'verbose_name_plural': 'Snapshots de Planes de Tratamiento',
                'ordering': ['-fecha_snapshot'],
                'indexes': [models.Index(fields=['historial_clinico'], name='clinical_re_histori_a2bdf6_idx'), models.Index(fields=['plan_original_id'], name='clinical_re_plan_or_4ed9cc_idx'), models.Index(fields=['-fecha_snapshot'], name='clinical_re_fecha_s_e1c5d7_idx')],
            },
        ),
    ]
