# Generated by Django 5.1.6 on 2026-02-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0011_plantratamientosnapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanTratamientoSnapshot',
        ),
    ]
